### ISSUE TITLE
No live updating, all outputs at the end

### ISSUE THREAD

**Issue by samwho** [cheggaaa/pb#105]
Before you scream "you need to call bar.Start()!" hear me out.

I'm running the example exactly as provided in your README.md (except with a smaller count so I don't have to wait as long):

```
$ cat bin/testpb.go
package main

import (
	"gopkg.in/cheggaaa/pb.v1"
	"time"
)

func main() {
	count := 1000
	bar := pb.StartNew(count)
	for i := 0; i < count; i++ {
		bar.Increment()
		time.Sleep(time.Millisecond)
	}
	bar.FinishPrint("The End!")
}
```

But when I run it it doesn't output anything until the very end, where it outputs 100%:

```
$ go run bin/testpb.go
 1000 / 1000 [==================================] 100.00% 3s
The End!
```

I'm on Arch Linux installed on VirtualBox using rxvt-unicode as my terminal, inside a tmux session (though I can confirm that it doesn't work outside of the tmux session either). Please let me know what other information you need to debug this.

**Comment by samwho** [comment]
I installed xterm to check if it was the terminal but I get exactly the same results in xterm.

**Comment by cheggaaa** [comment]
Thank you for the report! My bad I missed this bug in previous PR #103 
Now it's fixed and the new version released!

**Comment by samwho** [comment]
Thank you for the quick turnaround on this! I'll confirm whether this works when I'm home from work later. :)

**Comment by samwho** [comment]
Yup, this works. Thanks again!
