### ISSUE TITLE
v2 - re-add NewProxyReader?

### ISSUE THREAD

**Issue by zachgersh** [cheggaaa/pb#114]
Really appreciate the amount of work that has gone into pb! Wanted to ask, were there plans to put `NewProxyReader` back into v2? Now that v2 doesn't conform to `io.Writer` we are pretty much stuck (since you can't wire up your own `io.TeeReader`

**Comment by cheggaaa** [comment]
Done :)
(https://github.com/cheggaaa/pb/commit/50a44eddb5320e10977227110407f6f74a73808c)
v2.0.5 published

**Comment by zachgersh** [comment]
@cheggaaa 👍
