### ISSUE TITLE
Rolling pool of bars

### ISSUE THREAD

**Issue by psaffrey-illumina** [cheggaaa/pb#125]
I want to use pb to keep progress bars for an updating set of concurrent uploads, where as one upload finishes another takes its place. Is there a good way to do this? I can't see a way to remove a bar from a Pool - or should I just keep adding to the list? 

I'm also interested in usage patterns for progress bar pools. I can either create a pool and gradually add bars as I make them (StartPool() with an empty list followed by multiple Add() calls), or I can collect a group of bars and add them in bulk (StartPool() with a full list). Which do you recommend? I found that if I used the first and there was some lag before I added my first bar, the cursor moved up a line and started eating the previous text in my terminal.

I've realised this might be two issues - let me know if you want me to separate them or provide some example code.

**Comment by cheggaaa** [comment]
You must call StartPool with at least one bar. Later you can Add more bars, but can't remove them.
For your case, I think we need realize``` bar.Reset(total int)``` method and you will be able to reuse bars.

**Comment by cheggaaa** [comment]
You can use v2 it's fully thread safe.
https://github.com/cheggaaa/pb/tree/v2

**Comment by psaffrey-illumina** [comment]
I would like to use V2 but I'm interested specifically in concurrent progress over readers and I didn't see examples there - is this all possible in V2?

**Comment by cheggaaa** [comment]
sorry, accidentally clicked on close, now reopened

v2 does not support multiple bars as yet...

**Comment by psaffrey-illumina** [comment]
I find that even if I StartPool with one bar, it still consumes the old text from the terminal. I also tried declaring a block of bars and adding a bar afterwards - it's this adding after the pool has been created that causes it to move all the bars up one line consuming old text.

I like the idea of having a pool of bars each displaying the progress for the currently active area. Then you can imagine having a "master" bar that sits above the others telling you how many have already completed.

**Comment by psaffrey-illumina** [comment]
My apologies, I didn't see that you'd already fixed this :) thanks.
