### ISSUE TITLE
Have ProgressBar implement Read instead of Reader

### ISSUE THREAD

**Issue by joshlf** [cheggaaa/pb#13]
It might be more natural for ProgressBar to accept a reader (either as an exported member variable or as an unexported member variable and an exported setter), and then implement Read itself instead of having the separate Reader type.

**Comment by jszwedko** [comment]
Yeah, that seems reasonable, for new I just use `io.TeeReader`.

**Comment by Lupus** [comment]
I found NewProxyReader by chance via looking into this issue. It's worth mentioning it in readme along with MultiWriter approach for io operations.

BTW greate library! keep up the good job!
