### ISSUE TITLE
v3 is "huge"

### ISSUE THREAD

**Issue by cognusion** [cheggaaa/pb#151]
I love pb, and saw there was a v3. I dropped it in and recompiled one of my pb-using apps, and it gained 10M in size (it looks like 9M below, because rounding). Thinking maybe it was a new Go version or something else I reverted the pbv3 change and rebuilt, and it was back to "normal"

```bash
-rwxrwxr-x  1 M M  11M Jul  9 13:24 allv2
-rwxrwxr-x  1 M M  20M Jul  9 13:26 allv3
```

I haven't dug into the details of this, but wondering if this is expected?

**Comment by cheggaaa** [comment]
Thanks for your kind words!
So, on my linux (go version go1.12 linux/amd64), I'm built all versions with basic examples:
```
-rwxr-xr-x  1 che  che  2640251 Jul 10 01:51 v1*
-rwxr-xr-x  1 che  che  3936681 Jul 10 01:52 v2*
-rwxr-xr-x  1 che  che  3941408 Jul 10 01:50 v3*
```
As you can see v2 and v3 has the near sizes.

Do you use go modules? I can assume that the pb and your code has one library in dependencies, but with different versions, and compiler built both (i think the biggest dependency is golang.org/x/sys).

**Comment by cognusion** [comment]
Yes, for trivial applications I see similar results. I'm hoping to have some time today to do some more size analysis with [bloaty](https://github.com/google/bloaty/). Unfortunately, its Go symbol support is rough, so it takes methodical reproduction and incremental comparisons to really expose where increases are.

With respect to modules, I disabled them for those builds, as building with Go mods adds their own overhead (+4M on the v3 and +3m on the v2) and also makes size analysis cumbersome. 

Thanks for the response. I'm not "concerned", and certainly don't see any performance impact, just caught off-guard by the near-doubling of a binary I know too well. :grin:

**Comment by cognusion** [comment]
After switching off to a less-complicated project to use for size analysis, rebuilding with pb3 vs pb2 actually *decreased* the binary size, so I'll close this out and embrace random chaos. Thanks again for a great progress bar. :smile: 

```bash
-rwxrwxr-x 1 M M  9537805 Jul 10 10:50 wgetpipe.pb2
-rwxrwxr-x 1 M M  9517654 Jul 10 10:50 wgetpipe.pb3
```
