### ISSUE TITLE
v3 Unable to use few characters in Cycle

### ISSUE THREAD

**Issue by blueelvis** [cheggaaa/pb#152]
Hi!

Thanks a lot for your hard work! I was trying to implement this using the following template string but it is not working. I tried with other possible combinations and it was working fine. This is the following template string -
```
tmpl := `{{ string . "filePath" }} {{ bar . "<" "-" (cycle . "-" "\" "|" "/" ) "." ">"}} {{speed . }} {{percent .}} {{ rtime . " --%s remaining-- "}} {{ etime . " --%s elapsed-- "}}`
```
If I use the above template, it gets reset to default. All the elements after the cycle are ignored.

I am thinking it could be because there are some special characters?

-Pranav

**Comment by cheggaaa** [comment]
Thank you!
Try to replace `"\"` to `"\\"` in cycle arguments. Looks like it's escaping in go templates.

**Comment by blueelvis** [comment]
@cheggaaa - Yep, that worked! I put in the double slashes and it worked and looking really nice! Closing this issue. Thanks!
