### ISSUE TITLE
Broken gopkg.in/cheggaaa/pb.v3

### ISSUE THREAD

**Issue by gmelillo** [cheggaaa/pb#155]
I use to import this package from `gopkg.in` but, checking on the site the `v3` is supported but if I try to update keeping `gopkg.in` I got this nice error:

```
Command failed: go get -d ./...
go: finding gopkg.in/cheggaaa/pb.v3 v3.0.1
go: gopkg.in/cheggaaa/pb.v3@v3.0.1: go.mod has non-....v3 module path "github.com/cheggaaa/pb" at revision v3.0.1
go: error loading module requirements
```

There are some way to keep using gopkg?

**Comment by cheggaaa** [comment]
Sadly, but gopkg and go.mod can't work together.
You can look for similar issue https://github.com/mattn/go-colorable/issues/35

**Comment by Akaame** [comment]
@cheggaaa can you close this as it seems it is a `non-issue` for this library?
