### ISSUE TITLE
How to stop bytes being formatted?

### ISSUE THREAD

**Issue by darkermatter** [cheggaaa/pb#156]
I have this ```bar.Set(pb.Bytes, false)``` in my code to stop formatting.

This snippet from pb.go seems to imply that what I'm doing is right:
```
// Format convert int64 to string according to the current settings
func (pb *ProgressBar) Format(v int64) string {
	if pb.GetBool(Bytes) {
		return formatBytes(v)
	}
	return strconv.FormatInt(v, 10)
}
```

What am I missing?

Thanks!

**Comment by darkermatter** [comment]
Okay, I figured it out...
I need to call ```bar.Set(pb.Bytes, false)``` after ```bar.NewProxyReader(file)```.

**Comment by cheggaaa** [comment]
Yes. By default, ProxyReader sets Bytes format to true
