### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by kaustubhcs** [cheggaaa/pb#168]
```
Cannot use 'pb.Full.Start(int(elementCount))' (type *"github.com/cheggaaa/pb/v3".ProgressBar) as type *"github.com/cheggaaa/pb".ProgressBar
```

Anyway around this error?

**Comment by cheggaaa** [comment]
Looks like you trying to use both v1 and v3 together.
Check your import path and choose one of:
- import "github.com/cheggaaa/pb" - for v1
- import "github.com/cheggaaa/pb/v3" - for v3
