### ISSUE TITLE
Not display console

### ISSUE THREAD

**Issue by ody5sey** [cheggaaa/pb#169]
The program can set not display,I want to let the user choose

**Comment by cheggaaa** [comment]
So, you can handle pb's output as you want.

**Comment by ody5sey** [comment]
How, and has API?

**Comment by cheggaaa** [comment]
I don't know what you mean about no display. But you can set your own writer where you can control when and what you want to write.
```golang
bar.SetOutput(yourOwnWriter)
```
Or do not start the bar and just take the rendered string from ```bar.String()```

**Comment by ody5sey** [comment]
Oh yes, This is my want
`	
file, _ := os.Create("shadow.txt")
	
bar.SetWriter(file)
`
