### ISSUE TITLE
bar.ShowBar undefined (type *pb.ProgressBar has no field or method ShowBar)

### ISSUE THREAD

**Issue by LeKDTrey5** [cheggaaa/pb#178]
```
import "github.com/cheggaaa/pb/v3"

...
bar := new(pb.ProgressBar)
bar.ShowBar = false
...
```

I don't know exactly what the problem is

**Comment by cheggaaa** [comment]
The problem is you import v3, but code from v1.
You can import v1 ```import "github.com/cheggaaa/pb"```
Or use v3 and disable bar via template

**Comment by LeKDTrey5** [comment]
Oh well, thanks.
