### ISSUE TITLE
How can I clean the process bar before I want to output something.

### ISSUE THREAD

**Issue by PassingFoam** [cheggaaa/pb#179]
![image](https://user-images.githubusercontent.com/41845204/112618460-1a59d980-8e61-11eb-9b65-bab980e8c83a.png)
When I print anything ,the bar will be broken

**Comment by cheggaaa** [comment]
You can't print anything while progress is active. 
But you can print something compact into the bar (for eample ```bar.Set("prefix", "some logs")```)

**Comment by PassingFoam** [comment]
I think you can add a func to clean the bar,like the processbar.clean() in https://github.com/schollz/progressbar

**Comment by cheggaaa** [comment]
```bar.Set(pb.CleanOnFinish, true)``` will do it on finish

**Comment by PassingFoam** [comment]
I mean the (https://pkg.go.dev/github.com/schollz/progressbar/v3#ProgressBar.Clear) ,if I want to print something, I can clear the process bar and it will be working expectably in the next line

**Comment by cheggaaa** [comment]
This can't work as you expected. My implementation does render in the separate goroutine and text will be replaced on the next tick. In your example, the progress prints when you set or change something.

**Comment by PassingFoam** [comment]
Thank you for your patient reply
