### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by thalesfsp** [cheggaaa/pb#184]
Can it spin like (https://github.com/briandowns/spinner)?

Cheers!

**Comment by cheggaaa** [comment]
Yes! Just place `cycle` in your template, like this:
```(cycle . "↖" "↗" "↘" "↙" )```

**Comment by rmasci** [comment]
I'm not getting where to put this. I put it in like this: bar.SetTemplate({{ bar. ""(cycle. "↖" "↗" "↘" "↙" ) }}) and it errors. Could I get a full example?
