### ISSUE TITLE
ProgressBar Pool on Windows: Inconsistent printing on Windows when using ProgressBarTemplate

### ISSUE THREAD

**Issue by vyasgun** [cheggaaa/pb#213]
I am trying to use `Pool` to print progressbars with a custom template but adding the color attribute is causing unexpected output on Windows. A workaround that seems to fix this is by turning off the `RawMode`

Test code:

```
package main

import (
	"fmt"
	"math/rand"
	"time"

	"github.com/cheggaaa/pb/v3"
)

func main() {
	tmpl := `{{  red "first" }} {{ bar . "[" "|" "|" "-" "]" }} {{ percent . }} `
	myBar := pb.ProgressBarTemplate(tmpl).New(101)
	myPool := pb.NewPool(myBar)
	err := myPool.Start()
	if err != nil {
		fmt.Println("Error starting pool", err)
	}
	defer func() {
		if err := myPool.Stop(); err != nil {
			fmt.Println("Error stopping pool", err)
		}
	}()
	for i := 0; i < 10; i++ {
		myBar.SetTotal(100)
		myBar.SetCurrent(rand.Int63() % 101)
		time.Sleep(time.Second)
	}
}
```
Expected output:
<img width="1241" alt="Screenshot 2024-01-17 221701" src="https://github.com/cheggaaa/pb/assets/87057902/c008d524-1591-4849-b0bc-df54687dcf74">

Actual output:
<img width="1215" alt="Screenshot 2024-01-17 221713" src="https://github.com/cheggaaa/pb/assets/87057902/474a1c71-0ed4-4e83-9282-05f2d7279331">

The issue goes away on Windows by turning off the raw mode after starting the pool:
```
if runtime.GOOS == "windows" {
	if err := termutil.RawModeOff(); err != nil {
		fmt.Println("Error turning off raw mode", err)
	}
}
```

**Comment by cheggaaa** [comment]
Did you check it with the Windows command line or powershell? Because it could be different for IDE terminal

**Comment by vyasgun** [comment]
Yes, I have.

- Powershell: 
<img width="1276" alt="Screenshot 2024-01-22 160057" src="https://github.com/cheggaaa/pb/assets/87057902/9c16ca30-dc58-4460-b096-97a27f12f4d3">

- cmd:

<img width="1280" alt="Screenshot 2024-01-22 160128" src="https://github.com/cheggaaa/pb/assets/87057902/b902286f-885b-491a-8775-38f7aa4806ba">

**Comment by gbraad** [comment]
FYI: We had several of our users reports this; https://github.com/crc-org/crc/issues/3936. At first we thought this was related to Windows Terminal or an IDE hosted terminal, but seems the console host does the same.

![daemon1](https://github.com/crc-org/crc/assets/695993/f3a8798b-1a26-4d3e-8d3e-f6fb93b0b850)
