### ISSUE TITLE
Copyright confusion

### ISSUE THREAD

**Issue by penguin359** [cheggaaa/pb#217]
I am trying to package this software for Debian and get it's license and copyright correct. It appears that all this software is under a standard 3-clause BSD license, but I see two different copyrights listed. In [termios_sysv.go](https://github.com/cheggaaa/pb/blob/7667f987657572d6e2ad0c4f188c3f549916a448/termios_sysv.go#L1), it shows "Copyright 2013 The Go Authors.", but in the top-level [LICENSE](https://github.com/cheggaaa/pb/blob/7667f987657572d6e2ad0c4f188c3f549916a448/LICENSE#L1) file, it has "Copyright (c) 2012-2015, Sergey Cherepanov". Are these under different copyrights or which should I use for Debian? Are both valid for all files?

**Comment by cheggaaa** [comment]
Hi! Probably you found an old artifact. The library uses a standard 3-clause BSD license.
I fixed it in #218
