### ISSUE TITLE
How to implement Multiple Progress Bars???

### ISSUE THREAD

**Issue by marcellodesales** [cheggaaa/pb#31]
Problem
-----

Hi there,

I have a list of files being downloaded by different go routines...

```go
        for i := 0; i < len(urls); i++ {
                go func() { c <- download(urls[i])() }()
        }
```

I added the `pb()` implementation and it shows the progress bar, but it only displays in the same line... 

Feature Request
----------

* Is there a way to control which line the progress bar will be printed?
* If this is possible, I'd like to suggest the method "SetIndex" to set which line the progress must be printed after the current position on the terminal... 
* Any suggestions to change the Format method to do that?

```
// Sets the index of the progress, which gives the line position after the current terminal position.
func (pb *ProgressBar) SetIndex(index int) {}
```

This is similar to Docker's progress bars while pulling images...

```
[boot-1.pkg] 3.66 MB / 128.94 MB [==>------------------------------------------------] 2.84 % 759.61 KB/s 2m48s
[boot-2.pkg] 23.66 MB / 48.94 MB [===================>-------------------] 45.84 % 629.61 KB/s 2m48s
[boot-3.pkg] 30.00 MB / 300.94 MB [=====>------------------------------------------] 10.84 % 459.61 KB/s 2m48s
```

thanks!
Marcello

**Comment by uetchy** [comment]
Any updates?
I guess that it looks good to merge `multiple` branch into master.

**Comment by cheggaaa** [comment]
So far it's alpha.. We have not windows support and have some problems with catching os signals

**Comment by uetchy** [comment]
Did you checked out [go-keybind](https://github.com/k0kubun/go-keybind) ? This library can catch user inputs and supports windows.

**Comment by GideonRed** [comment]
Any chance you can merge some minimal support for multiple progress bars into master? Doesn't have to satisfy every requirement set in this issue. Just something to give a few progress bars.

I can create the PR for you if you wish.

**Comment by cheggaaa** [comment]
Merged!
Code was cleaned and added some safety changes.
But anyway do not work at windows.

**Comment by Quentin-M** [comment]
Merged just in time! We planned to start using it today on the experimental branch :+1:
Thanks!

**Comment by mnvx** [comment]
@cheggaaa Thanks for great feature and example. Would be great to add `pbPool.Stop()` into end of [example](https://github.com/cheggaaa/pb/issues/31#issuecomment-67288612):

```golang
package main

import (
    "math/rand"
    "pb"
    "sync"
    "time"
)

func main() {
    pool := &pb.Pool{}
    first := pb.New(1000).Prefix("First ")
    second := pb.New(1000).Prefix("Second ")
    third := pb.New(1000).Prefix("Third ")
    pool.Add(first, second, third)
    pool.Start()
    wg := new(sync.WaitGroup)
    for _, bar := range []*pb.ProgressBar{first, second, third} {
        wg.Add(1)
        go func(cb *pb.ProgressBar) {
            for n := 0; n < 1000; n++ {
                cb.Increment()
                time.Sleep(time.Millisecond * time.Duration(rand.Intn(100)))
            }
            cb.Finish()
            wg.Done()
        }(bar)
    }
    wg.Wait()

    // Stop pool, else keyboard will be locked after execution (as minimum in Ubuntu)
    pbPool.Stop()
}
```
