### ISSUE TITLE
Add NetBSD support to pb

### ISSUE THREAD

**Issue by iamleot** [cheggaaa/pb#33]
Hello Sergey!
Please add NetBSD support to pb.

In order to do that just add "netbsd" (between freebsd and openbsd to keep it sorted asciibetically ;)) to pb_nix.go and pb_x.go.

I have tested that on NetBSD/amd64 7.99.4 (-current) with lang/go 1.4.1 using odeke-em/drive.

Thanks in advance for your attention!
Ciao,
L.

**Comment by cheggaaa** [comment]
Hello!
Done - https://github.com/cheggaaa/pb/commit/d21a66c8dce57a0b60d888b68df19d9607d9fb17
Can you test this on netbsd?

**Comment by iamleot** [comment]
Hello Sergey,

Sergey Cherepanov writes:
> Hello!
> Done - https://github.com/cheggaaa/pb/commit/d21a66c8dce57a0b60d888b68df19d9607d9fb17
> Can you test this on netbsd?
Tested and I can confirm that it works.


Thank you and keep up the good work!
Ciao,
L.

**Comment by cheggaaa** [comment]
Awesome!
