### ISSUE TITLE
Cannot set start value without messing up speed estimation

### ISSUE THREAD

**Issue by lambdaupb** [cheggaaa/pb#39]
When resuming a download I want to set the currentValue to the already finished amount.
But `bar.Set64(123)` will mess up the speed estimation for some time.

There should be the possibility to set a startvalue without affecting the speed estimation.

Thanks for the great library.

**Comment by cheggaaa** [comment]
Thank you for a report!
I fixed it.
```Go
// just set value before start
bar.Set(n).Start()
```
