### ISSUE TITLE
Possible to update the total number of items?

### ISSUE THREAD

**Issue by rhd** [cheggaaa/pb#50]
Hi,

If I'm scanning the file system for mp3s to process (for example), and I'd like to show a progress complete. As the scanning starts, I will find 1 mp3 and begin to process it so the bar could show 1/1. But then 9 more mp3s could be found. I'd like the bar to reset it self to 1/10. And so on. Is something like this possible? Eventually, all mp3s will be found. Say 1000 of them and I'd like to show the progress of them being processed.

Thanks!

**Comment by cheggaaa** [comment]
Hi!
Yes, just update bar.Total field
```go
bar := pb.StartNew(10)
bar.Total = 42
```

**Comment by rhd** [comment]
Thank you!
