### ISSUE TITLE
DATA RACE

### ISSUE THREAD

**Issue by jhautefeuille** [cheggaaa/pb#53]
I've a program where bar.Increment() is in goroutine.

I've check program with -race

WARNING: DATA RACE
Read by goroutine 7:
  github.com/cheggaaa/pb.(*ProgressBar).GetWidth()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:327 +0x37
  github.com/cheggaaa/pb.(*ProgressBar).write()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:227 +0x72
  github.com/cheggaaa/pb.(*ProgressBar).Update()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:344 +0x7d
  github.com/cheggaaa/pb.(*ProgressBar).writer()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:351 +0x40
Goroutine 7 (running) created at:
  github.com/cheggaaa/pb.(*ProgressBar).Start()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:105 +0x150
  github.com/cheggaaa/pb.StartNew()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:53 +0x3c
  main.main()

How can I correct this ?

**Comment by cheggaaa** [comment]
Hm...
Usually race detector prints  "read" and "write" goroutines
I see only "read" trace...

**Comment by cheggaaa** [comment]
or can you give me small code example where we can repeat this?

**Comment by jhautefeuille** [comment]
==================
WARNING: DATA RACE
Read by goroutine 7:
  github.com/cheggaaa/pb.(*ProgressBar).GetWidth()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:327 +0x37
  github.com/cheggaaa/pb.(*ProgressBar).write()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:227 +0x72
  github.com/cheggaaa/pb.(*ProgressBar).Update()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:344 +0x7d
  github.com/cheggaaa/pb.(*ProgressBar).writer()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:351 +0x40

Previous write by main goroutine:
  main.main()
      /home/julien/ownCloud/Coding/gocronfeed/src/gocronfeed.go:88 +0x492

Goroutine 7 (running) created at:
  github.com/cheggaaa/pb.(*ProgressBar).Start()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:105 +0x150
  github.com/cheggaaa/pb.StartNew()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:53 +0x3c
  main.main()
      /home/julien/ownCloud/Coding/gocronfeed/src/gocronfeed.go:87 +0x44d
==================
0 / 4 |                                                                | 0.00 % ==================
WARNING: DATA RACE
Read by goroutine 7:
  github.com/cheggaaa/pb.(*ProgressBar).write()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:247 +0x582
  github.com/cheggaaa/pb.(*ProgressBar).Update()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:344 +0x7d
  github.com/cheggaaa/pb.(*ProgressBar).writer()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:351 +0x40

Previous write by main goroutine:
  github.com/cheggaaa/pb.(*ProgressBar).Start()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:98 +0x60
  main.main()
      /home/julien/ownCloud/Coding/gocronfeed/src/gocronfeed.go:91 +0x52d

Goroutine 7 (running) created at:
  github.com/cheggaaa/pb.(*ProgressBar).Start()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:105 +0x150
  github.com/cheggaaa/pb.StartNew()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:53 +0x3c
  main.main()
      /home/julien/ownCloud/Coding/gocronfeed/src/gocronfeed.go:87 +0x44d
==================
0 / 4 |                                                                | 0.00 % ==================
WARNING: DATA RACE
Write by goroutine 7:
  github.com/cheggaaa/pb.(*ProgressBar).Update()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:345 +0x93
  github.com/cheggaaa/pb.(*ProgressBar).writer()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:351 +0x40

Previous read by goroutine 8:
  github.com/cheggaaa/pb.(*ProgressBar).Update()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:343 +0x59
  github.com/cheggaaa/pb.(*ProgressBar).writer()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:351 +0x40

Goroutine 7 (running) created at:
  github.com/cheggaaa/pb.(*ProgressBar).Start()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:105 +0x150
  github.com/cheggaaa/pb.StartNew()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:53 +0x3c
  main.main()
      /home/julien/ownCloud/Coding/gocronfeed/src/gocronfeed.go:87 +0x44d

Goroutine 8 (running) created at:
  github.com/cheggaaa/pb.(*ProgressBar).Start()
      /home/julien/go/src/github.com/cheggaaa/pb/pb.go:105 +0x150
  main.main()
      /home/julien/ownCloud/Coding/gocronfeed/src/gocronfeed.go:91 +0x52d

**Comment by cheggaaa** [comment]
Looks like you have start bar two times
> gocronfeed.go:91 - Start()
> gocronfeed.go:87 - StartNew()

Just replace pb.StartNew to pb.New

my bad - I have not checks for double start

**Comment by jhautefeuille** [comment]
It's perfect. It was indeed the problem. A big thank-you. I go wash my eyes.
