### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by dcbishop** [cheggaaa/pb#58]
Might be nice to allow fancy unicode symbols for a smoother look similar to Python's [tqdm](https://github.com/tqdm/tqdm)

With unicode multiple characters can represent percentages. 

A simple solution would be to allow extra characters in bar.Format and just split all the middle characters into percentage groups.

```
bar.Format("[█▉▊▋▌▍▎▏ ]")
```

https://github.com/pypa/pip/blob/develop/pip/_vendor/progress/bar.py#L63

**Comment by cheggaaa** [comment]
Now you can use any templates in [v2](https://github.com/cheggaaa/pb/tree/v2)
