### ISSUE TITLE
exponentially weighted moving average would provide more accurate "time left"

### ISSUE THREAD

**Issue by dgryski** [cheggaaa/pb#6]
Instead of using the global average time per entry to calculate the remaining time, using EWMA would give more weight to recent times per entry and would likely provide a more accurate estimate.

**Comment by fd0** [comment]
Hey, what's the current state here? I can see some commits by @harshavardhana, but I was unable to find any of them in the repo.

**Comment by harshavardhana** [comment]
> Hey, what's the current state here? I can see some commits by @harshavardhana, but I was unable to find any of them in the repo.

@cheggaaa decided not to do it @fd0 - it became complex and wasn't adding value.

**Comment by dgryski** [comment]
Here's the code I use for my own progress lines: https://github.com/dgryski/trifles/blob/master/ewmaest/ewmaest.go

**Comment by cheggaaa** [comment]
I'm doing the second version of the progress bar. With EWMA and other features. It's will be released soon)

**Comment by vbauerster** [comment]
Have a look at [mpb](https://github.com/vbauerster/mpb). It uses `ewmaest` based ETA.

**Comment by fd0** [comment]
Nice, thanks!

**Comment by cheggaaa** [comment]
Now it's realized in [v2](https://github.com/cheggaaa/pb/tree/v2)
