### ISSUE TITLE
pb is broken on Windows 10 with Go 1.6

### ISSUE THREAD

**Issue by mhils** [cheggaaa/pb#67]
Thanks for the awesome project. Unfortunately, it does not work on my system.
```
λ go get
# github.com/cheggaaa/pb
..\..\cheggaaa\pb\pb_win.go:45: undefined: word

λ go run foo
# github.com/cheggaaa/pb
..\..\cheggaaa\pb\pb_win.go:45: undefined: word
```

Windows 10x64, Go 1.6. Let me know if you need anything else.

Edit: After fixing this by adding `type word int16`, I now get `pb_win.go:60: undefined: buffer in buffer.dwSize`.

**Comment by cheggaaa** [comment]
oops.. thanks for issue!
we are broke win with last pull request
@harshavardhana

**Comment by harshavardhana** [comment]
> @harshavardhana I think you miss something

Yes my bad :(,  can we enable appbeyor builds for 'pb' so that we can catch this properly?

**Comment by Quentin-M** [comment]
Broken on Windows x64 / Go 1.6 --> ```undefined: pb.Pool```

**Comment by cheggaaa** [comment]
@Quentin-M where you see this error?
Multiple bars do not work on windows and should not be built
