### ISSUE TITLE
Speed is not given enough space

### ISSUE THREAD

**Issue by tomiaijo** [cheggaaa/pb#69]
Sample code:

```go
bar := pb.New64(size)
bar.Output = os.Stderr
bar.ShowSpeed = true
bar.Start()
```

This produces the following output on OSX 10.11.2 and iTerm:

`141680640 / 3839401984 [===>------------------------------------------------------------------------------]   3.69 % 29478097/s2m2s`

Should there be a space between "/s" and "2m2s"?

If unit is set to ``pb.U_BYTES``:

`106.88 MB / 3.58 GB [==>------------------------------------------------------------------------------------]   2.92 % 28.09 MB2m3s`

Should there be "/s" and at least one space before the time estimate?

**Comment by cheggaaa** [comment]
Thanks a lot!

**Comment by tomiaijo** [comment]
Thank you for the great library!

That fixes the former case, but the latter case is now as follows (no "/s" at the speed box):

``` 160.50 MB / 3.58 GB [====>--------------------------------------------------------------------------------------------------]   4.38% 46.26 MB 1m13s```

Also, now there is an extra whitespace at the beginning of the line. That is probably caused by [this](https://github.com/cheggaaa/pb/commit/bc5077ebb22258c90afd76329357f9617ffa47ea#diff-d4cff43ab09a9c56d49a047d8ed25163R267) change.

**Comment by cheggaaa** [comment]
Fixed!
