### ISSUE TITLE
broken on Debian / go 1.0.2

### ISSUE THREAD

**Issue by gre** [cheggaaa/pb#71]
/usr/lib/go/src/pkg/github.com/cheggaaa/pb/pb_x.go:103: undefined: signal.Stop

**Comment by cheggaaa** [comment]
Hm.. you need go 1.4 or later
I created tag https://github.com/cheggaaa/pb/tree/go1.0
this is the old version without multiple bars, maybe it's will work

**Comment by gre** [comment]
oh ok make sense, thanks
