### ISSUE TITLE
Using versioned URLs

### ISSUE THREAD

**Issue by petercolberg** [cheggaaa/pb#74]
Now that you tagged a first v1 version (#73), could you use [versioned URLs](https://gopkg.in) for the import path? This allows you to make a breaking change and increase the major version, without affecting users of the previous major version. All that is needed is the following substitution in `README` and `*_test.go`: 

`github.com/cheggaaa/pb` → `gopkg.in/cheggaaa/pb.v1`

It would be great if you could release v1.0.1 including this change.

**Comment by cheggaaa** [comment]
Thanx! This is what I've been wanting to do!
