### ISSUE TITLE
Can the readproxy be upgraded to support readcloser?

### ISSUE THREAD

**Issue by elico** [cheggaaa/pb#80]
I am trying to work with a request body and the progress bar is wrapping the body as a reader.
Can the readproxy be upgraded to support readcloser? or can a readcloserproxy be added?

**Comment by wjessop** [comment]
I'd like this too. I submitted a [pull request](https://github.com/cheggaaa/pb/pull/60) for this a while back but it didn't go anywhere, I currently use a fork that has the functionality.

**Comment by cheggaaa** [comment]
Now you can create pb.Reader with io.Reader or io.ReadCloser

**Comment by elico** [comment]
@cheggaaa Thanks, tested to work as expected for http response body.
I think it can be closed.
