### ISSUE TITLE
Why ProxyReader instead of TeeReader?

### ISSUE THREAD

**Issue by rasky** [cheggaaa/pb#85]
For my usages of `pb` with `io.Reader`, I always used `io.TeeReader`, such as:

``` go
// create and start bar
bar := pb.New(myDataLen).SetUnits(pb.U_BYTES)
bar.Start()

// my io.Reader
r := myReader

// my io.Writer
w := myWriter

io.Copy(w, io.TeeReader(r, bar))
```

Any reason why I should use `ProxyReader` instead?

**Comment by cheggaaa** [comment]
Just another way! ProxyReader more logical and little bit faster. 
+ ProxyReader implements io.Closer
But TeeReader good choice.
