### ISSUE TITLE
Handle `Total` atomically

### ISSUE THREAD

**Issue by rasky** [cheggaaa/pb#86]
I have a (admittedly uncommon) situation: I don't know the `Total` value beforehand, so I create a bar with `Total=0`, because I want to show the user that some progress is being made. After a while, I asynchronously acquire the size in a different goroutine; I currently set it manually into the progress bar with `bar.Total = x`, and it seems to work, but it's marked as data-race, as there are many other goroutines writing into the bar for updating it, so the `Total` variable is being read/write in a racy way.

Would it make sense to add a method `SetTotal()` to change the total with an atomic operation, and then always use atomic operations to read it? I can contribute a patch if you want.

**Comment by cheggaaa** [comment]
You are right! 'Total' is not safe.
PR are welcome.
But I make the second version of bar, more safe and flexible, without any public variables. It will be available next month (I hope)

**Comment by vbauerster** [comment]
Have a look at [mpb](https://github.com/vbauerster/mpb). It fallbacks to simple spinner if total <= 0.
But if you need to have SetTotal() method anyway, adding it will be race free.

**Comment by cheggaaa** [comment]
Now we have thread-safe methods `SetTotal` and `SetTotal64` in v1.
Also, you can use v2 it's fully thread-safe.
