### ISSUE TITLE
FinishPrint writes to os.Stdout even though pb.Output is set

### ISSUE THREAD

**Issue by andreaskoch** [cheggaaa/pb#87]
The FinishPrint method currently writes to os.Stdout instead of pb.Output:

```go
// End print and write string 'str'
func (pb *ProgressBar) FinishPrint(str string) {
	pb.Finish()
	fmt.Println(str)
}
```

see: https://github.com/cheggaaa/pb/commit/7f4253899ba18226b3c52aca004d298182360edc#commitcomment-18923803

**Comment by nmiyake** [comment]
I encountered this as well -- opened #89 as a PR to suggest a fix

**Comment by nmiyake** [comment]
Thanks for merging @cheggaaa ! Any chance you can tag v1.0.6 to make this and other changes available through `gopkg.in`? Not urgent as I can just vendor this repo directly for now, but wanted to mention it given that the last tag was in mid-July.

**Comment by cheggaaa** [comment]
@nmiyake I forgot about it))  v1.0.6 released!
