### ISSUE TITLE
Race between Pool.Start & Pool.Add

### ISSUE THREAD

**Issue by djherbis** [cheggaaa/pb#97]
Looks like your Pool.print implementation reads Pool.bars, which gets written to whenever you call Pool.Add. 

You should probably synchronize operations on the bars slice in the pool.

==================
WARNING: DATA RACE
Write at 0x00c04204da40 by goroutine 22:
  sync/atomic.AddInt64()
      C:/Go/src/runtime/race_amd64.s:276 +0xb
  gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Add64()
      D:/Dropbox/Go/src/gopkg.in/cheggaaa/pb.v1/pb.go:156 +0x4b
  gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Add()
      D:/Dropbox/Go/src/gopkg.in/cheggaaa/pb.v1/pb.go:152 +0x49
  main.(*pbReporter).Write()
      D:/Dropbox/Go/src/github.com/djherbis/watch/progress.go:27 +0x5d
  io.(*multiWriter).Write()
      C:/Go/src/io/multi.go:51 +0xb5
  io.copyBuffer()
      C:/Go/src/io/io.go:392 +0x1d8
  io.Copy()
      C:/Go/src/io/io.go:360 +0x85
  main.download()
      D:/Dropbox/Go/src/github.com/djherbis/watch/download.go:43 +0x32b
  main.remoteFile.Download()
      D:/Dropbox/Go/src/github.com/djherbis/watch/crawl.go:40 +0x5d
  main.downloadFiles.func1()
      D:/Dropbox/Go/src/github.com/djherbis/watch/crawl.go:46 +0x5d

Previous read at 0x00c04204da40 by goroutine 6:
  gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Start()
      D:/Dropbox/Go/src/gopkg.in/cheggaaa/pb.v1/pb.go:115 +0xc9
  gopkg.in/cheggaaa/pb%2ev1.(*Pool).Add()
      D:/Dropbox/Go/src/gopkg.in/cheggaaa/pb.v1/pool.go:35 +0xbf
  gopkg.in/cheggaaa/pb%2ev1.StartPool()
      D:/Dropbox/Go/src/gopkg.in/cheggaaa/pb.v1/pool.go:18 +0xca
  main.showProgress()
      D:/Dropbox/Go/src/github.com/djherbis/watch/progress.go:38 +0x171

**Comment by cheggaaa** [comment]
Thank You! This race and some others in "pool" were fixed.

**Comment by djherbis** [comment]
Thanks for the quick fix! I really like this lib so I appreciate the fix!

**Comment by cheggaaa** [comment]
@djherbis You are welcome! New version released and available over gopkg.in
