### ISSUE TITLE
Panic in pool_win.go (coordinates.Y is negative)

### ISSUE THREAD

**Issue by djherbis** [cheggaaa/pb#98]
[This line](https://github.com/cheggaaa/pb/blob/b70adc94d6d9454331a94dc3c5fee1858a38959b/pool_win.go#L17) sometimes ends up negative (not sure why), which then causes setCursorPos to return an error and this lib to panic.

The quick fix I did for myself was just to check if Y < 0 and set it Y = 0 (which seems to work), but you may want a better fix.

**Comment by cheggaaa** [comment]
I haven't Windows at now. Just followed your advice.
I think this panic was when you add new bar to already started pool (and this behavior were fixed in the previous commit #97)

**Comment by djherbis** [comment]
Yeah I agree that the race condition fix probably solved this issue as well (it was happening when I added another bar, and I found both issues together).

Thanks for adding the guard condition though, better safe than panic'd :)
